# Generated by Django 4.2.3 on 2023-08-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
