# Generated by Django 4.2.4 on 2023-08-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='location',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='street_1',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='street_2',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='apartment',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='county',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
