# Generated by Django 4.2.4 on 2023-08-29 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='end_date',
        ),
    ]
