# Generated by Django 4.2.4 on 2023-08-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_contract_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='agent_first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='agent_last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='tenant_first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='tenant_last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
