# Generated by Django 4.2.3 on 2023-08-03 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_bill_is_paid_bill_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_occupied',
        ),
        migrations.AddField(
            model_name='room',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.tenant'),
        ),
    ]
