# Generated by Django 4.2.3 on 2023-08-03 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_room_is_occupied_room_tenant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='property',
            new_name='apartment',
        ),
    ]
