# Generated by Django 4.2.3 on 2023-08-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_property_room_apartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
