# Generated by Django 4.2.3 on 2023-08-03 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_room_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
