# Generated by Django 4.2.3 on 2023-08-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_tenant_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='tenant',
        ),
        migrations.AddField(
            model_name='room',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
    ]
