# Generated by Django 4.2.3 on 2023-08-04 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_room_tenant_room_is_occupied'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Property',
            new_name='Apartment',
        ),
    ]
