# Generated by Django 4.2.3 on 2023-08-04 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_booking_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_completed',
        ),
    ]
