# Generated by Django 4.2.3 on 2023-08-05 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_booking_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='county',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='street_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='street_2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='zip_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
