# Generated by Django 4.2.3 on 2023-08-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_apartment_city_apartment_county_apartment_street_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='rooms'),
        ),
    ]
